//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHOVR___MODEL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static log4net defaultInstance = ((log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new log4net())));
        
        public static log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
