//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHOV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1.1.1")]
        public string IP_Primary {
            get {
                return ((string)(this["IP_Primary"]));
            }
            set {
                this["IP_Primary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1.1.1")]
        public string IP_Secondary {
            get {
                return ((string)(this["IP_Secondary"]));
            }
            set {
                this["IP_Secondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1.1.1")]
        public string IP_Output {
            get {
                return ((string)(this["IP_Output"]));
            }
            set {
                this["IP_Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IN 01  </string>
  <string>IN 02  </string>
  <string>IN 03  </string>
  <string>IN 04  </string>
  <string>IN 05  </string>
  <string>IN 06  </string>
  <string>IN 07  </string>
  <string>IN 08  </string>
  <string>IN 09  </string>
  <string>IN 10  </string>
  <string>IN 11  </string>
  <string>IN 12  </string>
  <string>IN 13  </string>
  <string>IN 14  </string>
  <string>IN 15  </string>
  <string>IN 16  </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NamesInputPrimary {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NamesInputPrimary"]));
            }
            set {
                this["NamesInputPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IN 01  </string>
  <string>IN 02  </string>
  <string>IN 03  </string>
  <string>IN 04  </string>
  <string>IN 05  </string>
  <string>IN 06  </string>
  <string>IN 07  </string>
  <string>IN 08  </string>
  <string>IN 09  </string>
  <string>IN 10  </string>
  <string>IN 11  </string>
  <string>IN 12  </string>
  <string>IN 13  </string>
  <string>IN 14  </string>
  <string>IN 15  </string>
  <string>IN 16  </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NamesInputSecondary {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NamesInputSecondary"]));
            }
            set {
                this["NamesInputSecondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>OUT 01 </string>
  <string>OUT 02 </string>
  <string>OUT 03 </string>
  <string>OUT 04 </string>
  <string>OUT 05 </string>
  <string>OUT 06 </string>
  <string>OUT 07 </string>
  <string>OUT 08 </string>
  <string>OUT 09 </string>
  <string>OUT 10 </string>
  <string>OUT 11 </string>
  <string>OUT 12 </string>
  <string>OUT 13 </string>
  <string>OUT 14 </string>
  <string>OUT 15 </string>
  <string>OUT 16 </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NamesOutput {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NamesOutput"]));
            }
            set {
                this["NamesOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Change Over")]
        public string System {
            get {
                return ((string)(this["System"]));
            }
            set {
                this["System"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Primary")]
        public string DeviceChg0 {
            get {
                return ((string)(this["DeviceChg0"]));
            }
            set {
                this["DeviceChg0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IN 16  ")]
        public string InputDeviceChg0 {
            get {
                return ((string)(this["InputDeviceChg0"]));
            }
            set {
                this["InputDeviceChg0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Primary")]
        public string CurrentSelection {
            get {
                return ((string)(this["CurrentSelection"]));
            }
            set {
                this["CurrentSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/SystemLog")]
        public string Path_LogOperation {
            get {
                return ((string)(this["Path_LogOperation"]));
            }
            set {
                this["Path_LogOperation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLog {
            get {
                return ((bool)(this["EnableLog"]));
            }
            set {
                this["EnableLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/SystemLog")]
        public string SystemLog {
            get {
                return ((string)(this["SystemLog"]));
            }
            set {
                this["SystemLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int MaxSizeLog {
            get {
                return ((int)(this["MaxSizeLog"]));
            }
            set {
                this["MaxSizeLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
  <string>TRUE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatawrittenLog {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatawrittenLog"]));
            }
            set {
                this["DatawrittenLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>[ Primary  :     IN 01 ] 'IN 01  ' [ AND ] [ Secondary:     IN 02 ] 'IN 02  ' --[ OUT 03 ] 'OUT 03 '</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Combinations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Combinations"]));
            }
            set {
                this["Combinations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int SizeDgv {
            get {
                return ((int)(this["SizeDgv"]));
            }
            set {
                this["SizeDgv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableCombinationsLog {
            get {
                return ((bool)(this["EnableCombinationsLog"]));
            }
            set {
                this["EnableCombinationsLog"] = value;
            }
        }
    }
}
